services:
#    yoda_event.example:
#        class: Yoda\EventBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  event_report_manager:
    class: Yoda\EventBundle\Reporting\EventReportManager
    arguments: [@doctrine.orm.entity_manager, @router]

  twig.event_extension:
    class: Yoda\EventBundle\Twig\EventExtension
    arguments: []
    tags:
      - {name: twig.extension}