security:
    encoders:
        Yoda\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_database_user:
            entity: {class: UserBundle:User, property: username}



    firewalls:
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login_form
            logout:
                path:   logout
                target: event
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
#    put security  into controller
#        - { path: ^/new, roles: ROLE_USER }
#        - { path: ^/create, roles: ROLE_USER }
