<?php

namespace Yoda\EventBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Yoda\EventBundle\Entity\Event;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function getUpcomingEvents($max = null) {
        $qb = $this->createQueryBuilder('e')
            ->addOrderBy('e.time', 'ASC')
            ->andWhere('e.time > :now')->setParameter(':now', new \DateTime());

        if($max){
            $qb
                ->setMaxResults($max);
        }

        return $qb
            ->getQuery()
            ->execute();
    }

    /**
     * @return Event[]
     */
    public function getRecentlyUpdatedEvents(){
        $events = $this->createQueryBuilder('e')
            ->andWhere('e.updatedAt > :evdate')
            ->setParameter('evdate', new \DateTime('24 hours ago'))
            ->orderBy('e.updatedAt', 'ASC')
            ->getQuery()
            ->execute();

        return $events;
    }
}
